### ISSUE TITLE
Connection Error: Cannot connect to host www.linkedin.com:443 ssl:None [None]

### ISSUE THREAD

**Issue by ghost** [liranbg/linkedin-learning-downloader#3] opened 2018-09-02 15:11 UTC
Hi,
first of all, thank you for the work you've done. I installed and ran the tool: it manages to log into linkedin, it properly creates a folder for each video within the "downloads" folder, but then when it should start downloading the actual videos, it gives the following error: "Connection Error: Cannot connect to host www.linkedin.com:443 ssl:None [None]". 
Do you have any advice?
thanks,
Paolo

**Comment by Olvinsh** [comment] 2018-09-06 09:05
Is there any solution to this? Can anyone Advise ..Thanks

**Comment by liranbg** [comment] 2018-09-06 10:27
I tried to reproduce but no luck,
Can you access https://www.linkedin.com from the machine in which you are trying to run the script?

**Comment by liranbg** [comment] 2018-09-06 10:38
[This might help you overcome this issue](https://stackoverflow.com/questions/40347726/python-3-5-asyncio-and-aiohttp-errno-101-network-is-unreachable)

Change the relevant code where it crashes, let me know if it solved

**Comment by Olvinsh** [comment] 2018-09-06 10:57
I am able to access and I sent you a private message.
The above solution did not work for me. the program is fetching courses but not downloading
Can you please share the zip file compressed from mclmza's linkedin-learning-downloader
to my email nolivieira@gmail.com.

I would really appreciate.

**Comment by hmspisharody** [comment] 2018-10-17 23:21
I got this problem too. I think it happens when the number of videos to be downloaded (the queue) is too large. I don't know the exact number but I feel if the download can be coded to happen in bulks, for eg., 10 or 20 at at a time and then next bulk and so on, this problem can be solved.

**Comment by homapm** [comment] 2018-10-18 13:02
I got this problem too, with one course to download and nothing happens. Can it be the result of async calling? Appreciate any answer. Thanks.

**Comment by vincthedwarf** [comment] 2018-10-30 20:18
I am a Premium Linkedin user.
I am using python 2 on a Mac.
Type 'python2 llcd.py' in the terminal
I did the test and everything is working well on my side.
This script doesn't download the exercise files only the videos.
You can easily find the exercise files on Linkedin Learning.
You will find the scripts here:
https://drive.google.com/file/d/1tH2YNL6jyGWxJ6TsgH9eH_rYZa3IAxsS/view?usp=sharing

**Comment by armandhammer** [comment] 2019-01-10 17:02
I'm seeing the same error when I try to include more than one course / slug in the config so it does seem to have something to do with overloading the queue. Everything seems to go smoothly (logs in fine, etc) but then I get a "Connection Error". If I reduce my config down to only 1 course, I don't get this error anymore and it SEEMS to start downloading all of the video files just fine (on my Mac I see all of the videos appear in the directories in various states of download completion) BUT THEN after a few minutes of downloading at 1 MB/sec (not nearly long enough to fetch 2+ hours of video tutorials) I get this:

`ERROR    [!] Error while downloading: ''
Traceback (most recent call last):
  File "linkedin_learning.py", line 197, in download_file
    chunk = await r.content.read(1024)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 366, in read
    await self._wait('read')
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 297, in _wait
    await waiter
  File "/usr/local/lib/python3.7/site-packages/aiohttp/helpers.py", line 585, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
`

(this repeats many times, for seemingly every video file it was downloading for the course) and THEN all of the video files that were in various states of download completion are no longer on my Mac, and I am left with only ONE complete video file and all of the subtitle files remaining.

Very strange. This script seems SO CLOSE to working. Is there any way the project owner liranbg  can fix this?

**Comment by vincthedwarf** [comment] 2019-01-10 17:15
Hi Bengarland,

I will test with more than one course and come back to you.

**Comment by armandhammer** [comment] 2019-01-11 01:11
> Hi Bengarland,
> 
> I will test with more than one course and come back to you.

Thank you. If it is important, I was trying to download the courses 'music-production-secrets-larry-crane-on-recording' and 'audio-recording-techniques'. It failed. Then when I tried only the first one (music-production-secrets.....) it started downloading the video files, but did not finish and gave me the error above.

**Comment by vincthedwarf** [comment] 2019-01-11 01:14
Ok I will test the same on my side. Will give updates tomorrow.

**Comment by armandhammer** [comment] 2019-01-11 01:17
Also, I had to do the trick to remove the check for "access DENIED" because it would not work at all unless I commented those lines in the script, like this:

`logging.info(f'[*] Access to {course.name} is {"GRANTED" if course.unlocked else "DENIED"}')
        # if not course.unlocked:
            # Nothing to do here
            # return`

Seen here: [https://github.com/liranbg/linkedin-learning-downloader/issues/11](https://github.com/liranbg/linkedin-learning-downloader/issues/11)

**Comment by vincthedwarf** [comment] 2019-01-11 01:21
Are you a Linkedin premium member?

**Comment by armandhammer** [comment] 2019-01-11 01:40
Yes, I can log in and view the videos fine on LinkedIn, and I don't have 2 Factor Authentication enabled either. It should work. And it appears that (here on GitHub) several other people are having the same problems.

**Comment by armandhammer** [comment] 2019-01-11 04:12
I tried on a faster internet connection (9.5 MBytes/sec) and had some more success — it didn't give me any errors this time and said it was "finished". However, when I go look at the folders on my drive, every movie file exists BUT the data isn't all there so the files don't play (some files are 0.3 MB instead of something bigger, like 60 MB which they should be). It seems random. Some files are fully downloaded and play fine, others are not.

I don't know what is happening, because the script is telling me:

`INFO     [*] Finished  fetching course "Audio Recording Techniques"`
`INFO     [*] -------------Done-------------`

**Comment by armandhammer** [comment] 2019-01-12 01:08
I still don't know what is going on. Shorter courses seem to download fine, while courses with many videos (more than 30? I don't know) seem to not completely download all videos before it's "Done". The way I work around it is to download a course multiple times, and then merge the contents. Usually downloading about 3 or 4 times will be enough so that combining the successfully completed videos from each one will result in a 100% complete master set.

For a few courses, I have had to manually download a handful of missing videos in **Firefox**:

1) Navigate to the video on the LinkedIn Learning website
2) Select 720p video quality
3) Go to the "Page Info" window (CMD-I on Mac), select Media tab
4) Find and copy the Video URL (.mp4 file) — download this

**Comment by liranbg** [comment] 2019-08-13 16:51
fixed on #21 && #22

**Closed as completed by liranbg** 2019-08-13 16:51 UTC
